// src/app/terms/page.tsx — Theme-aware
import type { Metadata } from 'next';
import { Navbar } from '@/components/layout/navbar';
import { Footer } from '@/components/layout/footer';
import { ShieldAlert, UserCheck, PlayCircle, Scale, CreditCard, Ban, FileWarning } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service – PDFAI Hub',
  description: 'Read the PDFAI Hub Terms of Service. Learn about user responsibilities, acceptable use, billing policies, and disclaimers.',
};

export default function TermsOfServicePage() {
  const terms = [
    {
      icon: UserCheck,
      title: 'Acceptance of Terms',
      content: `By accessing or using the services provided by PDFAI Hub (including all PDF converters, summarizers, chat utilities, and revision tools), you agree to be bound by these Terms of Service. If you do not agree to all terms, you must immediately cease using the platform.`,
    },
    {
      icon: PlayCircle,
      title: 'User Responsibilities & Accounts',
      content: `You are responsible for safeguarding your login credentials (such as your Google OAuth session) and all activities occurring under your account:
      - You must provide accurate, current, and complete details during sign-up.
      - You are solely responsible for all content (documents, text, messages) uploaded or generated by you.`,
    },
    {
      icon: ShieldAlert,
      title: 'Acceptable Use',
      content: `You agree not to use PDFAI Hub for any unlawful purpose or to violate any local, national, or international regulations:
      - You must not upload viruses, malware, or destructive code.
      - You must not attempt to reverse engineer, scrape, or extract source code from the website's document tools or AI models.
      - You must not upload copyrighted, illegal, or abusive content.`,
    },
    {
      icon: FileWarning,
      title: 'AI-Generated Content Disclaimer',
      content: `PDFAI Hub employs state-of-the-art Large Language Models (LLMs) to generate summaries, chat responses, flashcards, and quizzes:
      - **No Guarantee**: AI is subject to hallucinations and may generate inaccurate, incomplete, or outdated content.
      - **Verification**: You are solely responsible for validating the accuracy of any AI-generated summaries, flashcard answers, or quiz questions prior to relying on them.
      - We hold no liability for academic, professional, or financial decisions made based on AI output.`,
    },
    {
      icon: CreditCard,
      title: 'Payment, Subscription & Refund Policy',
      content: `We offer a free version with daily limitations alongside premium, paid subscriptions:
      - **Billing**: Premium subscriptions are billed in advance on a recurring monthly or yearly cycle.
      - **Stripe/Razorpay**: Payments are handled securely. You authorize recurring charges to your selected payment method until cancellation.
      - **Cancellation**: You can cancel your subscription at any time through the Billing dashboard. Access remains until the billing cycle ends.
      - **Refund Policy**: Since we provide free trial quotas and pay third-party API providers for document processing immediately, all premium purchases are final. Refunds are only issued in cases of verified billing errors or system malfunctions.`,
    },
    {
      icon: Ban,
      title: 'Account Termination',
      content: `We reserve the right to suspend, limit, or terminate your access to PDFAI Hub at our sole discretion, without prior notice, if we believe your actions violate these Terms of Service, pose security risks, or cause financial or technical harm to the platform or other users.`,
    },
    {
      icon: Scale,
      title: 'Limitation of Liability',
      content: `PDFAI Hub and its parent, developers, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the service. This includes document processing delays, database downtime, file delivery failures, or inaccuracies in summaries.`,
    },
  ];

  return (
    <div className="min-h-screen bg-background text-foreground transition-colors duration-300">
      <Navbar />

      <main className="pt-24 pb-20">
        {/* Header */}
        <section className="relative overflow-hidden bg-hero-gradient py-12 border-b border-border transition-colors duration-300">
          <div className="section-container relative z-10 max-w-4xl mx-auto">
            <span className="text-xs bg-primary/10 text-primary px-3.5 py-1.5 rounded-full font-semibold uppercase tracking-wider">
              Legal Center
            </span>
            <h1 className="text-4xl font-bold mt-4 mb-2 text-foreground">
              Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground">
              Last Updated: July 5, 2026
            </p>
          </div>
        </section>

        {/* Content */}
        <section className="py-16">
          <div className="section-container max-w-4xl mx-auto">
            <div className="grid grid-cols-1 gap-8">
              {/* Introduction */}
              <div className="bg-card border border-border p-6 sm:p-8 rounded-2xl transition-colors duration-300">
                <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
                  Please read these Terms of Service carefully before using PDFAI Hub. By accessing or using our website, you agree to comply with and be bound by the conditions described below. These terms apply to all visitors, registered users, and premium subscribers.
                </p>
              </div>

              {/* Main Sections */}
              {terms.map((term, idx) => {
                const Icon = term.icon;
                return (
                  <div key={idx} className="bg-card border border-border p-6 sm:p-8 rounded-2xl space-y-4 transition-colors duration-300">
                    <h2 className="text-xl font-bold text-foreground flex items-center gap-3">
                      <div className="w-9 h-9 rounded-lg bg-primary/10 text-primary border border-primary/25 flex items-center justify-center flex-shrink-0">
                        <Icon className="w-4.5 h-4.5" />
                      </div>
                      {term.title}
                    </h2>
                    <div className="text-sm text-muted-foreground leading-relaxed pl-12">
                      {term.content}
                    </div>
                  </div>
                );
              })}

              {/* Intellectual Property and Changes */}
              <div className="bg-card border border-border p-6 sm:p-8 rounded-2xl space-y-4 transition-colors duration-300">
                <h2 className="text-xl font-bold text-foreground pl-12">
                  Intellectual Property & Changes to Terms
                </h2>
                <div className="text-sm text-muted-foreground leading-relaxed pl-12 space-y-4">
                  <p>
                    <strong>Intellectual Property:</strong> The code, design, branding, and proprietary assets of PDFAI Hub belong exclusively to the site developers and are protected under international copyright and trademark laws. You may not duplicate, copy, or reuse any portion of our visual designs or backend code without express written consent.
                  </p>
                  <p>
                    <strong>Changes to Terms:</strong> We reserve the right to modify these Terms of Service at any time. If changes are substantial, we will publish the updated terms on this page and revise the &quot;Last Updated&quot; date. Continued use of the platform after updates indicates consent.
                  </p>
                </div>
              </div>

              {/* Contact Email */}
              <div className="bg-primary/5 border border-primary/20 p-6 sm:p-8 rounded-2xl text-center space-y-3 transition-colors duration-300">
                <h3 className="text-lg font-bold text-foreground">Questions About Our Terms of Service?</h3>
                <p className="text-sm text-muted-foreground max-w-lg mx-auto">
                  If you have legal inquiries, billing questions, or require clarity regarding acceptable use guidelines, please contact our legal desk.
                </p>
                <a
                  href="mailto:pdfaihub@gmail.com"
                  className="inline-block text-base font-bold text-primary hover:underline"
                >
                  pdfaihub@gmail.com
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
